AllCops:
  TargetRubyVersion: 2.6.5

Style/Documentation:
  Enabled: true

Layout/LineLength:
  Enabled: true
  Max: 120

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses

Lint/RequireParentheses:
  Enabled: false

# New cops:
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
